name = "dcmfx_core"
description = "DCMfx - Core Library"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "dcmfx", repo = "dcmfx" }
gleam = ">= 1.5.1"

[dependencies]
bigi = ">= 3.2.0 and < 4.0.0"
envoy = ">= 1.0.1 and < 2.0.0"
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
ieee_float = ">= 1.0.2 and < 2.0.0"
term_size = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
typescript_declarations = true
