name = "dcmfx_core"
version = "0.31.0"
description = "DCMfx core library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.11.1"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_core"

[dependencies]
bigi = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.61.0 and < 2.0.0"
ieee_float = ">= 1.5.0 and < 2.0.0"
term_size = ">= 1.0.1 and < 2.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev-dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleeunit = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
