name = "dcmfx_pixel_data"
description = "DCMfx pixel data library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.6.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_pixel_data"

[dependencies]
bigi = ">= 3.2.0 and < 4.0.0"
dcmfx_core = { path = "../dcmfx_core" }
gleam_stdlib = ">= 0.46.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
