name = "dcmfx_pixel_data"
version = "0.21.0"
description = "DCMfx pixel data library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.11.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_pixel_data"

[dependencies]
bigi = ">= 3.2.2 and < 4.0.0"
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_p10 = { path = "../dcmfx_p10" }
gleam_stdlib = ">= 0.60.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.1 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
