name = "dcmfx_pixel_data"
version = "0.30.0"
description = "DCMfx pixel data library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.11.1"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_pixel_data"

[dependencies]
bigi = ">= 4.0.0 and < 5.0.0"
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_p10 = { path = "../dcmfx_p10" }
gleam_stdlib = ">= 0.61.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
