[package]
name = "dcmfx_character_set"
description = "DCMfx character set library"

repository.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
version.workspace = true
homepage.workspace = true
keywords.workspace = true

[features]
default = ["std"]
std = []
