preset: conventionalcommits
presetConfig:
  types:
    - type: feat
      section: Features
    - type: fix
      section: Bug Fixes
    - type: docs
      scope: lib
      section: Documentation
      hidden: false
    - type: refactor
      section: Refactors

plugins:
  - - "@semantic-release/commit-analyzer"

    # Until v1.0 is designated all breaking changes are minor releases and
    # everything else is a patch
    - releaseRules:
        - breaking: true
          release: minor
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          scope: lib
          release: patch
        - type: perf
          release: patch

  - "@semantic-release/release-notes-generator"

  - - "@semantic-release/git"

    # The following files are committed as part of the release commit
    - assets:
        - examples/*/gleam/gleam.toml
        - examples/*/gleam/manifest.toml
        - examples/*/rust/Cargo.toml
        - examples/Cargo.lock
        - src/gleam/*/gleam.toml
        - src/gleam/*/manifest.toml
        - src/gleam/dcmfx_p10/src/dcmfx_p10/uids.gleam
        - src/rust/*/Cargo.lock
        - src/rust/*/Cargo.toml

      message: "chore: Release v${nextRelease.version}"

  - - "@semantic-release/github"

    # Include all the builds for all platforms in the release on GitHub
    - assets:
        - path: "dcmfx-*/*"
