preset: conventionalcommits
presetConfig:
  types:
    - type: feat
      section: Features
    - type: fix
      section: Bug Fixes
    - type: docs
      scope: lib
      section: Documentation
      hidden: false
    - type: refactor
      section: Refactors

plugins:
  - - "@semantic-release/commit-analyzer"

    # Until v1.0 is designated all breaking changes are minor releases and
    # everything else is a patch
    - releaseRules:
        - breaking: true
          release: minor
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: docs
          scope: lib
          release: patch
        - type: perf
          release: patch

  - "@semantic-release/release-notes-generator"

  - - "@semantic-release/github"

    - assets:
        - path: "dcmfx-*/*"
