name = "dcmfx_integration_tests"
description = "DCMfx integration tests"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.6.0"

[dependencies]
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_json = { path = "../dcmfx_json" }
dcmfx_p10 = { path = "../dcmfx_p10" }
gleam_json = ">= 2.1.0 and < 3.0.0"
gleam_stdlib = ">= 0.46.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
file_streams = ">= 1.2.2 and < 2.0.0"

[javascript]
deno = { allow_read = true, allow_write = true }
