name = "dcmfx_character_set"
description = "DCMfx - Character Set Library"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "dcmfx", repo = "dcmfx" }
gleam = ">= 1.5.0"

[dependencies]
gleam_stdlib = ">= 0.41.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
typescript_declarations = true
