name = "dcmfx_character_set"
version = "0.34.0"
description = "DCMfx character set library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.12.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_character_set"

[dependencies]
gleam_stdlib = ">= 0.61.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
