name = "data_set_anonymize"

[dependencies]
dcmfx_anonymize = { path = "../../../src/gleam/dcmfx_anonymize" }
dcmfx_core = { path = "../../../src/gleam/dcmfx_core" }
dcmfx_p10 = { path = "../../../src/gleam/dcmfx_p10" }
gleam_stdlib = ">= 0.45.0 and < 2.0.0"

[javascript]
deno = { allow_env = true, allow_read = true }
