name = "dicom_stream"

[dependencies]
dcmfx_core = { path = "../../../src/gleam/dcmfx_core" }
dcmfx_p10 = { path = "../../../src/gleam/dcmfx_p10" }
gleam_stdlib = ">= 0.40.0 and < 2.0.0"
file_streams = ">= 1.1.1 and < 2.0.0"
