name = "pixel_data_read"

[dependencies]
dcmfx_core = { path = "../../../src/gleam/dcmfx_core" }
dcmfx_p10 = { path = "../../../src/gleam/dcmfx_p10" }
dcmfx_pixel_data = { path = "../../../src/gleam/dcmfx_pixel_data" }
gleam_stdlib = ">= 0.41.0 and < 2.0.0"
