name = "dcmfx_json"
version = "0.35.1"
description = "DCMfx JSON library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.13.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_json"

[dependencies]
bigi = ">= 4.1.0 and < 5.0.0"
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_p10 = { path = "../dcmfx_p10" }
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_stdlib = ">= 0.65.0 and < 2.0.0"
ieee_float = ">= 1.6.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.1 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
