name = "dcmfx_p10"
description = "DCMfx Part 10 library"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "dcmfx", repo = "dcmfx" }
gleam = ">= 1.5.0"

[dependencies]
dcmfx_character_set = { path = "../dcmfx_character_set" }
dcmfx_core = { path = "../dcmfx_core" }
file_streams = ">= 1.2.0 and < 2.0.0"
gleam_stdlib = ">= 0.41.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
typescript_declarations = true
