name = "dcmfx_p10"
description = "DCMfx - Part 10 Library"
licences = ["AGPL-3.0-only"]
repository = { type = "github", user = "dcmfx", repo = "dcmfx" }
gleam = ">= 1.5.1"

[dependencies]
file_streams = ">= 1.1.1 and < 2.0.0"
dcmfx_core = { path = "../dcmfx_core" }
dcmfx_character_set = { path = "../dcmfx_character_set" }
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"

[javascript]
typescript_declarations = true
