name = "dcmfx_p10"
version = "0.18.0"
description = "DCMfx Part 10 library"
licences = ["AGPL-3.0-only"]
gleam = ">= 1.9.0"

[repository]
type = "github"
user = "dcmfx"
repo = "dcmfx"
path = "src/gleam/dcmfx_p10"

[dependencies]
dcmfx_character_set = { path = "../dcmfx_character_set" }
dcmfx_core = { path = "../dcmfx_core" }
file_streams = ">= 1.5.0 and < 2.0.0"
gleam_deque = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.3.1 and < 2.0.0"

[javascript]
typescript_declarations = true
deno = { allow_read = true }
