name: Release

on: push

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  check_semantic_release:
    name: Check semantic release
    timeout-minutes: 30
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Semantic release dry run
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
          extra_plugins: conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for tests to complete
        if: steps.semantic-release.outputs.new_release_published == 'true'
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Test

  build_rust_cli_tool:
    name: Build Rust CLI tool
    timeout-minutes: 30

    needs: check_semantic_release
    if: needs.check_semantic_release.outputs.new_release_published == 'true'

    strategy:
      matrix:
        rust-target:
          # - aarch64-apple-darwin
          # - aarch64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          # - x86_64-pc-windows-msvc
          # - x86_64-unknown-linux-musl
        include:
          # - rust-target: aarch64-apple-darwin
          #   toolchain: aarch64-apple-darwin
          #   runs-on: macos-14
          # - rust-target: aarch64-unknown-linux-musl
          #   toolchain: x86_64-unknown-linux-gnu
          #   musl-target: aarch64-linux-musl
          #   runs-on: ubuntu-24.04
          - rust-target: armv7-unknown-linux-musleabihf
            toolchain: x86_64-unknown-linux-gnu
            musl-target: armv7l-linux-musleabihf
            runs-on: ubuntu-24.04
          # - rust-target: x86_64-pc-windows-msvc
          #   toolchain: x86_64-pc-windows-msvc
          #   runs-on: windows-2025
          # - rust-target: x86_64-unknown-linux-musl
          #   toolchain: x86_64-unknown-linux-gnu
          #   musl-target: x86_64-linux-musl
          #   runs-on: ubuntu-24.04

    runs-on: ${{ matrix.runs-on }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.93-${{ matrix.toolchain }}"
          cache-workspaces: src/rust
          target: ${{ matrix.rust-target }}

      - name: Setup musl toolchain (Linux)
        if: matrix.rust-target == 'aarch64-unknown-linux-musl' || matrix.rust-target == 'x86_64-unknown-linux-musl' || matrix.rust-target == 'armv7-unknown-linux-musleabihf'
        run: |
          # Download and install the musl toolchain into /opt/musl-cross
          wget -q https://dcmfx.s3.ap-southeast-2.amazonaws.com/build-tools/${{ matrix.musl-target }}-cross.tgz
          tar -xzf ${{ matrix.musl-target }}-cross.tgz
          mv ${{ matrix.musl-target }}-cross /opt/musl-cross
          echo "/opt/musl-cross/bin" >> $GITHUB_PATH

          # Create musl-* symlinks for the toolchain
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-ar /opt/musl-cross/bin/musl-ar
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-g++ /opt/musl-cross/bin/musl-g++
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-gcc /opt/musl-cross/bin/musl-gcc
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-ld /opt/musl-cross/bin/musl-ld
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-nm /opt/musl-cross/bin/musl-nm
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-ranlib /opt/musl-cross/bin/musl-ranlib
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-strings /opt/musl-cross/bin/musl-strings
          ln -s /opt/musl-cross/bin/${{ matrix.musl-target }}-strip /opt/musl-cross/bin/musl-strip

          RUST_TARGET=${{ matrix.rust-target }}
          RUST_TARGET="${RUST_TARGET//-/_}"

          echo "CC_${RUST_TARGET}=musl-gcc" >> $GITHUB_ENV
          echo "CXX_${RUST_TARGET}=musl-g++" >> $GITHUB_ENV
          echo "AR_${RUST_TARGET}=musl-ar" >> $GITHUB_ENV

          # Override Cargo linker for the cross-compilation target
          RUST_TARGET="${RUST_TARGET^^}"
          echo "CARGO_TARGET_${RUST_TARGET}_LINKER=musl-gcc" >> $GITHUB_ENV

      - name: Fetch dependencies
        working-directory: src/rust
        run: cargo fetch --locked --target ${{ matrix.rust-target }}

      - name: Set crate versions
        uses: ./.github/actions/set_rust_crate_versions
        with:
          version: ${{ needs.check_semantic_release.outputs.new_release_version }}

      - name: Enable LTO for release builds
        working-directory: src/rust
        run: printf '\n[profile.release]\nlto = true\n' >> Cargo.toml

      - name: Build release binary
        working-directory: src/rust
        run: cargo build --release --offline --target ${{ matrix.rust-target }} --package dcmfx_cli

      - name: Package
        shell: bash
        run: |
          if [ "${{ matrix.rust-target }}" = "x86_64-pc-windows-msvc" ]; then
            ARCHIVE="dcmfx-v${{ needs.check_semantic_release.outputs.new_release_version }}-${{ matrix.rust-target }}.zip"
            cp src/rust/target/${{ matrix.rust-target }}/release/dcmfx_cli$BINARY_SUFFIX dcmfx.exe
            choco install zip -y --no-progress
            zip "$ARCHIVE" dcmfx.exe
          else
            ARCHIVE="dcmfx-v${{ needs.check_semantic_release.outputs.new_release_version }}-${{ matrix.rust-target }}.tar.gz"
            cp src/rust/target/${{ matrix.rust-target }}/release/dcmfx_cli$BINARY_SUFFIX dcmfx
            tar -czvf "$ARCHIVE" dcmfx
          fi

          openssl dgst -r -sha256 -out "$ARCHIVE".sha256 "$ARCHIVE"
          echo "ARCHIVE=$ARCHIVE" >> $GITHUB_ENV

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dcmfx-${{ matrix.rust-target }}
          path: |
            ${{ env.ARCHIVE }}
            ${{ env.ARCHIVE }}.sha256
          if-no-files-found: error
          retention-days: 1
